version: '3.1'
services:
  devc:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:z
    command: sleep infinity 
    # command: tail -f /dev/null
    depends_on:
      - rabbitmq

  rabbitmq:
    image: docker.io/rabbitmq:4.0-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: postgres
      RABBITMQ_DEFAULT_PASS: postgres
    ports:
      - "5672:5672"
      - "15672:15672"