name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build CLI for Linux
      run: GOOS=linux GOARCH=amd64 go build -o rabbitmqdemo ./src

    - name: Build CLI for Windows
      run: GOOS=windows GOARCH=amd64 go build -o rabbitmqdemo.exe ./src

    - name: Build Docker CLI image
      run: |
        echo 'FROM scratch' > Dockerfile
        echo 'COPY rabbitmqdemo /app' >> Dockerfile
        docker build -t rabbitmqdemo:latest .

    - name: Upload Linux binary
      uses: actions/upload-artifact@v3
      with:
        name: rabbitmqdemo-linux
        path: rabbitmqdemo

    - name: Upload Windows binary
      uses: actions/upload-artifact@v3
      with:
        name: rabbitmqdemo-windows
        path: rabbitmqdemo.exe
    
    - name: Upload Dockerfile
      uses: actions/upload-artifact@v3
      with:
        name: dockerfile
        path: Dockerfile
